CREATE  table If not exists users(
id integer generated by default as identity primary key,
name varchar(100),
email varchar(100) not null unique);


CREATE  table If not exists requests(
id integer generated by default as identity primary key,
description varchar not null,
user_id integer not null  references users(id),
time timestamp not null
);

CREATE  table If not exists items(
id integer generated by default as identity primary key,
name varchar(100) not null,
description varchar(100) not null,
available boolean not null,
user_id integer not null  references users(id),
request_id integer references requests(id)
);


CREATE  table If not exists bookings(
id integer generated by default as identity primary key,
starting timestamp  not null,
ending timestamp  not null,
item integer not null  references items(id),
booker integer not null   references users(id),
status varchar not null
);

CREATE  table If not exists comments(
id integer generated by default as identity primary key,
text varchar(100)  not null,
created timestamp  not null,
author_name varchar(40) not null,
item integer not null references items(id)
);